extends:
  - '@commitlint/config-conventional'
rules:
  type-enum:
    [
      2,
      'always',
      ['build', 'chore', 'ci', 'docs', 'feat', 'fix', 'docs', 'style', 'refactor', 'test', 'revert', 'blog']
    ]
