name: LintFormat

on:
  push:
    paths:
      - 'src/**/*'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 8.2.0

      - name: pnpm install
        run: pnpm i --frozen-lockfile

      - name: ESLint
        run: pnpm run lint

      - name: Prettier
        run: pnpm run format
