name: LintFormat

on:
  push:
    paths:
      - 'src/**/*'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.15.x'
      - name: pnpm install
        run: pnpm install
      - name: ESLint
        run: pnpm run lint
      - name: Prettier
        run: pnpm run format
